ORG_TO_TICKER = {
    "3M": "MMM",
    "AMD": "AMD",
    "AT&T": "T",
    "AbbVie": "ABBV",
    "Abbott Laboratories": "ABT",
    "Airbnb": "ABNB",
    "Alphabet": "GOOGL",
    "Amazon": "AMZN",
    "American Airlines": "AAL",
    "American Express": "AXP",
    "Amgen": "AMGN",
    "Anthem": "ELV",  # Formerly ANTM
    "Apple": "AAPL",
    "Baxter International": "BAX",
    "Berkshire Hathaway": "BRK.B",
    "Block": "SQ",  # Formerly Square
    "Boeing": "BA",
    "Boston Scientific": "BSX",
    "Bristol Myers Squibb": "BMY",
    "CVS Health": "CVS",
    "Caterpillar": "CAT",
    "Centene": "CNC",
    "Chevron": "CVX",
    "Cigna": "CI",
    "Coca-Cola": "KO",
    "Costco": "COST",
    "Delta Airlines": "DAL",
    "Eli Lilly": "LLY",
    "ExxonMobil": "XOM",
    "General Electric": "GE",
    "Gilead Sciences": "GILD",
    "Goldman Sachs": "GS",
    "HCA Healthcare": "HCA",
    "Home Depot": "HD",
    "Honeywell": "HON",
    "Humana": "HUM",
    "IBM": "IBM",
    "Intel": "INTC",
    "Intuitive Surgical": "ISRG",
    "JPMorgan Chase": "JPM",
    "Johnson & Johnson": "JNJ",
    "Johnson Controls": "JCI",
    "Kroger": "KR",
    "Lowe's": "LOW",
    "Lyft": "LYFT",
    "Mastercard": "MA",
    "McDonald's": "MCD",
    "Medtronic": "MDT",
    "Merck": "MRK",
    "Meta": "META",
    "Microsoft": "MSFT",
    "Morgan Stanley": "MS",
    "Mylan": "VTRS",  # Now part of Viatris
    "Netflix": "NFLX",
    "Nike": "NKE",
    "Nvidia": "NVDA",
    "Oracle": "ORCL",
    "Palantir": "PLTR",
    "PayPal": "PYPL",
    "PepsiCo": "PEP",
    "Pfizer": "PFE",
    "Pinterest": "PINS",
    "Procter & Gamble": "PG",
    "Regeneron": "REGN",
    "Roku": "ROKU",
    "Salesforce": "CRM",
    "Shopify": "SHOP",
    "Snap": "SNAP",
    "Spotify": "SPOT",
    "Starbucks": "SBUX",
    "Stryker": "SYK",
    "T-Mobile": "TMUS",
    "Target": "TGT",
    "Tesla": "TSLA",
    "The Walt Disney Company": "DIS",
    "Thermo Fisher Scientific": "TMO",
    "Uber": "UBER",
    "UnitedHealth Group": "UNH",
    "Verizon": "VZ",
    "Visa": "V",
    "Walgreens Boots Alliance": "WBA",
    "Walmart": "WMT",
    "Zimmer Biomet": "ZBH",
    "Zoom Video Communications": "ZM"
}
